#!/bin/bash
composer install
./bin/magento cache:flush
./bin/magento cache:disable
rm var/view_preprocessed/* -rf
rm var/cache/* -rf
rm var/log/* -rf
rm generated/* -rf
rm pub/static/* -rf
./bin/magento deploy:mode:set production -s
magerun config:set "dev/static/sign" 1
magerun config:set "dev/css/minify_files" 1
magerun config:set "dev/css/merge_css_files" 1
magerun config:set "dev/js/minify_files" 1
magerun config:set "dev/js/merge_files" 1
./bin/magento setup:upgrade
./bin/magento setup:di:compile
./bin/magento setup:static-content:deploy
./bin/magento cache:enable
read -p "Start testing and press any key to continue when finished. " -n1 -s
echo "Closing Developer mode..."
./bin/magento deploy:mode:set developer
magerun config:set "dev/static/sign" 0
magerun config:set "dev/css/minify_files" 0
magerun config:set "dev/css/merge_css_files" 0
magerun config:set "dev/js/minify_files" 0
magerun config:set "dev/js/merge_files" 0
./bin/magento cache:disable full_page
./bin/magento cache:clean
rm var/view_preprocessed/* -rf
rm var/cache/* -rf
rm var/log/* -rf
rm generated/* -rf
rm pub/static/* -rf