#!/bin/bash

if [[ -z "$1" ]]; then
  echo "Arguments: "
  echo "  help"
  echo "  purge"
  echo "  platform application name"
  exit 0
fi

if [[ $1 = "help" ]]; then
  echo "Available Environments:"
  ls ~/dev/docker/src/php | grep -v "default"
  echo "Available Applications:"
  ls ~/dev/docker/src/app | grep -v "default"
  exit 0
fi

if [[ $1 = "purge" ]]; then
  rm -rf .docker docker-compose.yml Dockerfile .env
  exit 0
fi

if [[ ! -d ~/dev/docker/src/php/$1 ]]; then
  echo "Unknown Environment $1"
  echo "Available Environments:"
  ls ~/dev/docker/src/php | grep -v "default"
  exit 0
fi

if [[ ! -d ~/dev/docker/src/app/$2 ]]; then
  echo "Unknown Application $1"
  echo "Available Applications:"
  ls ~/dev/docker/src/app | grep -v "default"
  exit 0
fi


mkdir .docker
mkdir .docker/etc
mkdir .docker/nginx
mkdir .docker/php
mkdir .docker/supervisor
mkdir .docker/tools

# ENV
cp ~/dev/docker/src/app/$2/.env .

# NGINX
cp ~/dev/docker/src/nginx/* .docker/nginx

# PHP
cp ~/dev/docker/src/php/$1/cli .docker/php/cli -r
cp ~/dev/docker/src/php/$1/fpm .docker/php/fpm -r
cp ~/dev/docker/src/php/$1/xdebug.ini .docker/php/

# SUPERVISORD
cat ~/dev/docker/src/php/default/supervisord.conf \
    ~/dev/docker/src/php/$1/supervisord.conf > .docker/supervisor/supervisord.conf

# ENTRYPOINT
cat ~/dev/docker/src/app/default/run-prefix.sh \
    ~/dev/docker/src/app/$2/run.sh > .docker/run.sh \
    ~/dev/docker/src/app/default/run-postfix.sh

# TOOLS
cp ~/dev/docker/src/app/default/tools/* .docker/tools
cp ~/dev/docker/src/app/$2/tools/* .docker/tools

# ETC
cp ~/dev/docker/src/app/$2/etc/* .docker/etc

# DOCKERFILE
cp ~/dev/docker/src/php/default/Dockerfile .
sed -i -e '/#_ENVIRONMENT_/{' -e "r ~/dev/docker/src/php/$1/Dockerfile" -e 'd' -e '}' Dockerfile
sed -i -e '/#_APPLICATION_/{' -e "r ~/dev/docker/src/php/$2/Dockerfile" -e 'd' -e '}' Dockerfile

echo "Docker compiled."

if [[ "$2" != "" ]]; then
  sed -i -e "s/<PROJECT>/$2/g" .env
  echo "Configuration files patched successfully."
fi

sed -i -e "s/<SHARED_UID>/$UID/" .env

echo "Type: 'Adjust .env file and... $ sudo docker-compose up' to build and start containers"
exit 0