#!/bin/bash

if [ -z "$1" ]; then
  echo "Arguments: "
  echo "  help"
  echo "  purge"
  echo "  container [domain.dev]"
  exit 0
fi

if [ $1 = "help" ]; then
  echo "Available containers:"
  ls ~/dev/docker | grep php
  exit 0
fi

if [ $1 = "purge" ]; then
  rm -rf .docker docker-compose.yml Dockerfile .env
  exit 0
fi

cp -r ~/dev/docker/$1/.docker .
cp -r ~/dev/docker/$1/Dockerfile .
cp -r ~/dev/docker/$1/docker-compose.yml .
cp -r ~/dev/docker/$1/.env .

echo "Docker initialized."

if [ "$2" != "" ]; then
  sed -i -e "s/<SITE-DOMAIN>/$2/" .env
  sed -i -e "s/<SITE-DOMAIN>/$2/" docker-compose.yml
  echo "Configuration files patched successfully."
fi

echo "Type: '$ sudo docker-compose up' to build and start containers"
exit 0