#!/bin/sh

if [ "$1" != "" ]; then
  lang=$1
else
  lang="en_US"
fi

switch_on_flag () {
    echo "Switching on: $1"
    ./bin/magento config:set $1 1 > /dev/null
}

switch_off_flag () {
    echo "Switching off: $1"
    ./bin/magento config:set $1 0 > /dev/null
}

echo "Deploying as: $lang"

composer install
./bin/magento cache:flush
./bin/magento cache:disable
rm var/view_preprocessed/* -rf
rm var/cache/* -rf
rm var/log/* -rf
rm generated/* -rf
rm pub/static/* -rf
./bin/magento deploy:mode:set production -s
switch_on_flag "dev/static/sign"
switch_on_flag "dev/css/minify_files"
switch_on_flag "dev/css/merge_css_files"
switch_on_flag "dev/js/minify_files"
switch_on_flag "dev/js/merge_files"
./bin/magento setup:upgrade
./bin/magento setup:di:compile
./bin/magento setup:static-content:deploy en_US --theme Magento/backend
./bin/magento setup:static-content:deploy $lang
./bin/magento cache:enable
read -p "Start testing and press any key to continue when finished Production Mode."
echo "Closing Production mode, reverting Developer mode..."
./bin/magento deploy:mode:set developer
switch_off_flag "dev/static/sign"
switch_off_flag "dev/css/minify_files"
switch_off_flag "dev/css/merge_css_files"
switch_off_flag "dev/js/minify_files"
switch_off_flag "dev/js/merge_files"
./bin/magento cache:disable full_page
./bin/magento cache:clean
rm var/view_preprocessed/* -rf
rm var/cache/* -rf
rm var/log/* -rf
rm generated/* -rf
rm pub/static/* -rf
