version: '3'
services:

  web:
    build:
      context: .
      args:
        - SHARED_UID
        - NODE_VERSION
        # Blackfire (remove if not necessary)
        - BLACKFIRE_ENABLED
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - .:%ROOT_PATH%
      - ${HOME}/.ssh:/root/.ssh
      - ${HOME}/.composer:/root/.composer
    links:
      - redis
      - mysql
      - mailcatcher
    env_file: .env
    environment:
      - PROJECT
      - VHOST_NAME
      - FASTCGI_TIMEOUT
      - PHP_MEMORY_LIMIT
      - CPU_COUNT
      - XDEBUG_REMOTE_HOST
      - XDEBUG_REMOTE_PORT
      - TIME_ZONE
      - MAGENTO_KEY
      - APP_USER_NAME
      - APP_USER_PASSWD
      - APP_USER_EMAIL
      - APP_USER_FIRST_NAME
      - APP_USER_LAST_NAME
      - APP_CURRENCY
      - APP_LOCALE
      - APP_TIMEZONE

  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - cache:/data

  mysql:
    image: percona:5.7
    ports:
      - "3306:3306"
    volumes:
    - db:/var/lib/mysql
    environment:
      - 'MYSQL_ROOT_PASSWORD=admin'
      - 'MYSQL_LOG_CONSOLE=true'
      - "MYSQL_ROOT_HOST=%"

  mailcatcher:
    image: schickling/mailcatcher
    ports:
      - '1080:1080'
      - '1025:1025'

  blackfire:
    image: blackfire/blackfire
    env_file: .env
    environment:
      - BLACKFIRE_CLIENT_ID
      - BLACKFIRE_CLIENT_TOKEN
      - BLACKFIRE_SERVER_ID
      - BLACKFIRE_SERVER_TOKEN
    ports:
      - "8707:8707"

volumes:
  db:
  cache: