version: '3'
services:

  web:
    build:
      context: .
      args:
        - SHARED_UID
        - NODE_VERSION
        - BLACKFIRE_ENABLED # remove if not necessary
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - .:%ROOT_PATH%
      - ${HOME}/.ssh:/root/.ssh
      - ${HOME}/.composer:/root/.composer
    links:
      - redis
      - mysql
      - mail
    env_file: .env

  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - cache:/data

  mysql:
    image: percona:5.7
    ports:
      - "3306:3306"
    volumes:
    - db:/var/lib/mysql
    environment:
      - 'MYSQL_ROOT_PASSWORD=admin'
      - 'MYSQL_LOG_CONSOLE=true'
      - "MYSQL_ROOT_HOST=%"

  mail:
    image: mailhog/mailhog
    ports:
      - '8025:8025'
      - '1025:1025'

  blackfire:
    image: blackfire/blackfire
    env_file: .env
    environment:
      - BLACKFIRE_CLIENT_ID
      - BLACKFIRE_CLIENT_TOKEN
      - BLACKFIRE_SERVER_ID
      - BLACKFIRE_SERVER_TOKEN
    ports:
      - "8707:8707"

volumes:
  db:
  cache: