version: '3'
services:

  web:
    build:
      context: .
      args:
        - SHARED_UID
        - NODE_VERSION
    ports:
      - "80:80"
    volumes:
      - .:/var/www/current/
      - ${HOME}/.ssh:/root/.ssh.back/
      - ${HOME}/.composer:/root/.composer.back
    links:
      - redis
      - mysql
      - mailcatcher
    env_file: .env
    environment:
      - PROJECT
      - VHOST_NAME
      - FASTCGI_TIMEOUT
      - PHP_MEMORY_LIMIT
      - XDEBUG_REMOTE_HOST
      - XDEBUG_REMOTE_PORT
      - TIME_ZONE
      - MAGENTO_KEY

  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - cache:/data

  mysql:
    image: percona:5.7
    ports:
      - "3306:3306"
    volumes:
    - db:/var/lib/mysql
    environment:
      - 'MYSQL_ROOT_PASSWORD=admin'
      - 'MYSQL_LOG_CONSOLE=true'
      - "MYSQL_ROOT_HOST=%"

  mailcatcher:
    image: schickling/mailcatcher
    ports:
      - '1080:1080'
      - '1025:1025'

volumes:
  db:
  cache: