version: '3'
services:

  web:
    build: .
    ports:
     - "80:80"
    volumes:
     - .:/var/www/current/
     - $HOME/.ssh:/root/.ssh.back/
     - $HOME/.composer:/root/.composer.back
    links:
     - redis
     - mysql
    env_file: .env
    environment:
      - 'SITE_DOMAIN=<SITE_DOMAIN>'
      - 'VHOST_NAME=default.conf'
      - 'FASTCGI_TIMEOUT=1800'
      - 'PHP_MEMORY_LIMIT=512M'
      - 'XDEBUG_REMOTE_HOST=172.17.0.1'
      - 'XDEBUG_REMOTE_PORT=9000'
      - 'TIME_ZONE="Europe/Warsaw"'

  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
    - cache:/data

  mysql:
    image: percona:5.5
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql
    environment:
     - 'MYSQL_ROOT_PASSWORD=admin'
     - 'MYSQL_LOG_CONSOLE=true'
     - "MYSQL_ROOT_HOST=%"

volumes:
  db:
  cache: