web:
  build: .
  ports:
   - "80:80"
  volumes:
   - .:/var/www/current/
   - USER_DIR/.ssh:/root/.ssh.back/
   - USER_DIR/.composer:/root/.composer.back
  links:
   - redis
   - mysql
  env_file: .env
  environment:
    - 'SITE_DOMAIN=SITE-DOMAIN'
    - 'FASTCGI_TIMEOUT=1800'
    - 'PHP_MEMORY_LIMIT=512M'
    - 'XDEBUG_REMOTE_HOST=127.0.0.1'
    - 'XDEBUG_REMOTE_PORT=9000'
    - 'TIME_ZONE="Europe/Warsaw"'
redis:
  image: redis
  ports:
    - "6379:6379"
mysql:
  image: mysql/mysql-server
  ports:

    - "3306:3306"
  volumes:
    - /mnt/docker/db/bedrenaetter:/var/lib/mysql
  environment:
   - 'MYSQL_ROOT_PASSWORD=admin'
